package com.vector.school.UI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.vector.school.App;
import com.vector.school.Controller.Home_controller;
import com.vector.school.model.Teacher;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Vector;

public class Home {
    private JButton signInButton;
    private JButton signUpButton;
    private JPanel homeJpanel;

    private JButton signInButton1;
    private JButton signUpButton1;
    private JPanel homeJpanel1;
    private Home_controller controller = new Home_controller();
    private List<Teacher> teacherList;

    public Home() {
        setUpUI();
        signInButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                App.frame.setContentPane(new User_sign_in().getSigninPanel());
                App.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                App.frame.pack();
                App.frame.setVisible(true);

            }
        });
        signUpButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                App.frame.setContentPane(new User_sign_up().getSignupPanel());
                App.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                App.frame.pack();
                App.frame.setVisible(true);
            }
        });



    }

    public void setUpUI() {
        teacherList = controller.get_all_teachers();
        int temp = 0;
        homeJpanel1 = new JPanel();

        homeJpanel1.setLayout(new GridLayoutManager(teacherList.size() + 1, 2, new Insets(15, 5, 5, 5), -1, -1));
        homeJpanel1.setBackground(new Color(-1));
        homeJpanel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Home", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$("Ubuntu", Font.BOLD, 18, homeJpanel1.getFont()), new Color(-8745488)));
        signInButton1 = new JButton();
        signInButton1.setBackground(new Color(-8745488));
        signInButton1.setText("sign in ");
        homeJpanel1.add(signInButton1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        signUpButton1 = new JButton();
        signUpButton1.setBackground(new Color(-8745488));
        signUpButton1.setText("sign up");
        homeJpanel1.add(signUpButton1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        for (Teacher teacher : teacherList) {
            temp += 1;
            JLabel label = new JLabel(teacher.getName());
            label.setName(teacher.getName());
            if (teacher.getAvailablity() != null) {
                if (!teacher.getAvailablity()) label.setBackground(new Color(0xD63B43));
                else {
                    label.setBackground(new Color(0x42F048));
                }
            }
            homeJpanel1.add(label, new GridConstraints(temp, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        }


    }

    public JPanel getHomeJpanel() {
        return homeJpanel1;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        homeJpanel = new JPanel();
        homeJpanel.setLayout(new GridLayoutManager(1, 2, new Insets(15, 5, 5, 5), -1, -1));
        homeJpanel.setBackground(new Color(-1));
        homeJpanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Home", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$("Ubuntu", Font.BOLD, 18, homeJpanel.getFont()), new Color(-8745488)));
        signInButton = new JButton();
        signInButton.setBackground(new Color(-8745488));
        signInButton.setText("sign in ");
        homeJpanel.add(signInButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        signUpButton = new JButton();
        signUpButton.setBackground(new Color(-8745488));
        signUpButton.setText("sign up");
        homeJpanel.add(signUpButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return homeJpanel;
    }

}
