package com.vector.school.UI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.vector.school.App;
import com.vector.school.Controller.Signin_controller;
import com.vector.school.model.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class User_sign_in {
    private JTextField usernameTextField;
    private JPasswordField passwordField;
    private JButton signInButton;
    private JPanel signinPanel;
    private JButton homeButton;
    private Signin_controller controller = new Signin_controller();

    public User_sign_in() {
        signInButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                User user = controller.signin_user(usernameTextField.getText(), String.valueOf(passwordField.getPassword()));
                if (user != null) {
                    App.cacheUser = user;
                    JOptionPane.showMessageDialog(null, " Sign in Success");
                    System.out.println(App.cacheUser.getUserrole());
                    if (App.cacheUser.getUserrole().equals("Teacher")) {
                        App.frame.setContentPane(new TeacherHome().getTeacherHomePanel());
                        App.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        App.frame.pack();
                        App.frame.setVisible(true);
                    } else if (App.cacheUser.getUserrole() == "Admin") {
                        App.frame.setContentPane(new AdminHome().getAdminHomePanel());
                        App.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        App.frame.pack();
                        App.frame.setVisible(true);
                    }


                } else {
                    JOptionPane.showMessageDialog(null, "Sign in Failed");
                }

            }
        });

        homeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                App.frame.setContentPane(new Home().getHomeJpanel());
                App.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                App.frame.pack();
                App.frame.setVisible(true);
            }
        });
    }

    public JPanel getSigninPanel() {
        return signinPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        signinPanel = new JPanel();
        signinPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        usernameTextField = new JTextField();
        signinPanel.add(usernameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Username");
        signinPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Password");
        signinPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField = new JPasswordField();
        signinPanel.add(passwordField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        signInButton = new JButton();
        signInButton.setText("Sign In");
        signinPanel.add(signInButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        homeButton = new JButton();
        homeButton.setText("Home");
        signinPanel.add(homeButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return signinPanel;
    }

}
